In [1]:
# Importando as Bibliotecas

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

def drop_reset_index(df):
    df = df.dropna()
    df = df.reset_index(drop=True)
    df.index += 1
    return df

In [9]:
url = 'https://www.football-data.co.uk/mmz4281/2324/E0.csv'

df = pd.read_csv(url)

In [10]:
df.columns.to_list()

['Div',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'VCH',
 'VCD',
 'VCA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'PSCH',
 'PSCD',
 'PSCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA']

In [11]:
colunas = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR','B365H','B365D','B365A','B365>2.5','B365<2.5']
colunas_renomeadas = ['Date','Home','Away','Goals_H','Goals_A','Result','Odd_H','Odd_D','Odd_A','Odd_Over25','Odd_Under25']

df = df[colunas]
df.columns = colunas_renomeadas

df = drop_reset_index(df)

display(df)

,Date,Home,Away,Goals_H,Goals_A,Result,Odd_H,Odd_D,Odd_A,Odd_Over25,Odd_Under25
1,11/08/2023,Burnley,Man City,0,3,A,8.00,5.5,1.33,1.67,2.20
2,12/08/2023,Arsenal,Nott'm Forest,2,1,H,1.18,7.0,15.00,1.44,2.75
3,12/08/2023,Bournemouth,West Ham,1,1,D,2.70,3.4,2.55,1.90,2.00
4,12/08/2023,Brighton,Luton,4,1,H,1.33,5.5,9.00,1.62,2.30
5,12/08/2023,Everton,Fulham,0,1,A,2.20,3.4,3.30,2.01,1.89
...,...,...,...,...,...,...,...,...,...,...,...
299,03/04/2024,Arsenal,Luton,2,0,H,1.10,10.0,19.00,1.25,4.00
300,03/04/2024,Brentford,Brighton,0,0,D,2.38,3.8,2.75,1.57,2.38
301,03/04/2024,Man City,Aston Villa,4,1,H,1.30,6.0,8.00,1.40,3.00
302,04/04/2024,Liverpool,Sheffield United,3,1,H,1.09,12.0,21.00,1.20,4.50
303,04/04/2024,Chelsea,Man United,4,3,H,2.00,4.0,3.40,1.40,3.00

In [13]:
df.to_excel("./Football_Data/Base_Football_Data.xlsx",index=False)

In [16]:
# Pegando de Várias Ligas

df1 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/F1.csv')
df2 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2223/F1.csv')
df3 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/F1.csv')
df4 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/I1.csv')
df5 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2223/I1.csv')
df6 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/I1.csv')
df7 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/D1.csv')
df8 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2223/D1.csv')
df9 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/D1.csv')
df10 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/SP1.csv')
df11 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2223/SP1.csv')
df12 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/SP1.csv')

df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])
df = df[['Date','HomeTeam','AwayTeam','FTHG','FTAG','B365H','B365D','B365A']]
df.columns = ['Date','Home','Away','Goals_H','Goals_A','Odd_H','Odd_D','Odd_A']

df = drop_reset_index(df)
df.to_excel("./Football_Data/Base_Football_Data.xlsx",index=False)
display(df)

,Date,Home,Away,Goals_H,Goals_A,Odd_H,Odd_D,Odd_A
1,06/08/2021,Monaco,Nantes,1,1,1.44,4.33,7.00
2,07/08/2021,Lyon,Brest,1,1,1.33,5.00,8.50
3,07/08/2021,Troyes,Paris SG,1,2,11.00,6.00,1.25
4,08/08/2021,Rennes,Lens,1,1,2.00,3.40,3.75
5,08/08/2021,Bordeaux,Clermont,0,2,2.00,3.40,3.75
...,...,...,...,...,...,...,...,...
3972,31/03/2024,Girona,Betis,3,2,1.75,3.80,4.75
3973,31/03/2024,Alaves,Sociedad,0,1,3.50,2.90,2.38
3974,31/03/2024,Real Madrid,Ath Bilbao,2,0,1.53,4.33,6.00
3975,01/04/2024,Villarreal,Ath Madrid,1,2,2.90,3.75,2.25
3976,04/04/2024,Granada,Valencia,0,1,3.40,3.10,2.30

In [21]:
# Jogos do Dia
jogos = pd.read_csv('https://www.football-data.co.uk/fixtures.csv')

colunas = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR','B365H','B365D','B365A','B365>2.5','B365<2.5']
colunas_renomeadas = ['Date','Home','Away','Goals_H','Goals_A','Result','Odd_H','Odd_D','Odd_A','Odd_Over25','Odd_Under25']

jogos = jogos[colunas]
jogos.columns = colunas_renomeadas

jogos.to_excel("./Football_Data/Jogos_Futuros.xlsx",index=False)