In [5]:
from futpythontrader_DEMO import *

import pandas as pd
import numpy as np
import requests
from datetime import date, datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

def drop_reset_index(df):
    df = df.dropna()
    df = df.reset_index(drop=True)
    df.index += 1
    return df

In [7]:
url = f"https://api.football-data-api.com/league-list?key={key}&chosen_leagues_only=true"
data = requests.get(url).json()['data']
dados = pd.DataFrame.from_dict(data).sort_values(['name'])
dados = drop_reset_index(dados)

new_df = []
for row in dados.itertuples():
    if isinstance(row.season, list):
        for season_info in row.season:
            new_df.append({
                'League': row.name,
                'ID': season_info['id'],
                'Season': season_info['year'],
                'Image': row.image
            })

new = pd.DataFrame(new_df)
new = drop_reset_index(new)

flt = new['Season'].isin([2023, 20222023, 2024, 20232024])
new2 = new[flt]
new2 = drop_reset_index(new2)
new2["Season"] = new2["Season"].astype(str)
new2["ID"] = new2["ID"].astype(str)
new2

,League,ID,Season,Image
1,Argentina Primera División,8595,2023,https://cdn.footystats.org/img/competitions/ar...
2,Argentina Primera División,11212,2024,https://cdn.footystats.org/img/competitions/ar...
3,Australia A-League,8008,20222023,https://cdn.footystats.org/img/competitions/au...
4,Australia A-League,10505,20232024,https://cdn.footystats.org/img/competitions/au...
5,Austria 2. Liga,7584,20222023,https://cdn.footystats.org/img/competitions/au...
...,...,...,...,...
120,USA MLS,10977,2024,https://cdn.footystats.org/img/competitions/us...
121,Uruguay Primera División,8937,2023,https://cdn.footystats.org/img/competitions/ur...
122,Uruguay Primera División,11209,2024,https://cdn.footystats.org/img/competitions/ur...
123,Wales Welsh Premier League,7620,20222023,https://cdn.footystats.org/img/competitions/wa...
124,Wales Welsh Premier League,9565,20232024,https://cdn.footystats.org/img/competitions/wa...

In [8]:
for a,b in zip(new2.ID,new2.League):
    print("df.replace("+a+",'"+b+"', inplace=True)")

df.replace(8595,'Argentina Primera División', inplace=True)
df.replace(11212,'Argentina Primera División', inplace=True)
df.replace(8008,'Australia A-League', inplace=True)
df.replace(10505,'Australia A-League', inplace=True)
df.replace(7584,'Austria 2. Liga', inplace=True)
df.replace(9641,'Austria 2. Liga', inplace=True)
df.replace(7890,'Austria Bundesliga', inplace=True)
df.replace(9954,'Austria Bundesliga', inplace=True)
df.replace(7572,'Belgium First Division B', inplace=True)
df.replace(9607,'Belgium First Division B', inplace=True)
df.replace(7544,'Belgium Pro League', inplace=True)
df.replace(9577,'Belgium Pro League', inplace=True)
df.replace(9035,'Brazil Serie A', inplace=True)
df.replace(11321,'Brazil Serie A', inplace=True)
df.replace(9042,'Brazil Serie B', inplace=True)
df.replace(11351,'Brazil Serie B', inplace=True)
df.replace(9087,'Brazil Serie C', inplace=True)
df.replace(11365,'Brazil Serie C', inplace=True)
df.replace(7483,'Bulgaria First League', inplace=True)
df.replace(9551,'Bulgaria First League', inplace=True)
df.replace(8833,'Chile Primera División', inplace=True)
df.replace(11103,'Chile Primera División', inplace=True)
df.replace(9186,'China Chinese Super League', inplace=True)
df.replace(11217,'China Chinese Super League', inplace=True)
df.replace(7457,'Croatia Prva HNL', inplace=True)
df.replace(9542,'Croatia Prva HNL', inplace=True)
df.replace(7586,'Czech Republic First League', inplace=True)
df.replace(9592,'Czech Republic First League', inplace=True)
df.replace(7426,'Denmark Superliga', inplace=True)
df.replace(9545,'Denmark Superliga', inplace=True)
df.replace(8520,'Egypt Egyptian Premier League', inplace=True)
df.replace(10652,'Egypt Egyptian Premier League', inplace=True)
df.replace(7593,'England Championship', inplace=True)
df.replace(9663,'England Championship', inplace=True)
df.replace(7570,'England EFL League One', inplace=True)
df.replace(9582,'England EFL League One', inplace=True)
df.replace(7574,'England EFL League Two', inplace=True)
df.replace(9581,'England EFL League Two', inplace=True)
df.replace(7704,'England Premier League', inplace=True)
df.replace(9660,'England Premier League', inplace=True)
df.replace(8898,'Estonia Meistriliiga', inplace=True)
df.replace(11119,'Estonia Meistriliiga', inplace=True)
df.replace(7455,'Europe UEFA Champions League', inplace=True)
df.replace(9543,'Europe UEFA Champions League', inplace=True)
df.replace(8935,'Finland Veikkausliiga', inplace=True)
df.replace(11120,'Finland Veikkausliiga', inplace=True)
df.replace(7500,'France Ligue 1', inplace=True)
df.replace(9674,'France Ligue 1', inplace=True)
df.replace(7501,'France Ligue 2', inplace=True)
df.replace(9621,'France Ligue 2', inplace=True)
df.replace(7499,'Germany 2. Bundesliga', inplace=True)
df.replace(9656,'Germany 2. Bundesliga', inplace=True)
df.replace(7591,'Germany 3. Liga', inplace=True)
df.replace(9741,'Germany 3. Liga', inplace=True)
df.replace(7664,'Germany Bundesliga', inplace=True)
df.replace(9655,'Germany Bundesliga', inplace=True)
df.replace(7954,'Greece Super League', inplace=True)
df.replace(9889,'Greece Super League', inplace=True)
df.replace(8784,'Iceland Úrvalsdeild', inplace=True)
df.replace(10975,'Iceland Úrvalsdeild', inplace=True)
df.replace(7608,'Italy Serie A', inplace=True)
df.replace(9697,'Italy Serie A', inplace=True)
df.replace(7864,'Italy Serie B', inplace=True)
df.replace(9808,'Italy Serie B', inplace=True)
df.replace(8810,'Japan J1 League', inplace=True)
df.replace(10994,'Japan J1 League', inplace=True)
df.replace(8811,'Japan J2 League', inplace=True)
df.replace(10995,'Japan J2 League', inplace=True)
df.replace(7484,'Netherlands Eerste Divisie', inplace=True)
df.replace(9654,'Netherlands Eerste Divisie', inplace=True)
df.replace(7482,'Netherlands Eredivisie', inplace=True)
df.replace(9653,'Netherlands Eredivisie', inplace=True)
df.replace(8739,'Norway Eliteserien', inplace=True)
df.replace(10976,'Norway Eliteserien', inplace=True)
df.replace(8740,'Norway First Division', inplace=True)
df.replace(10986,'Norway First Division', inplace=True)
df.replace(8783,'Paraguay Division Profesional', inplace=True)
df.replace(11141,'Paraguay Division Profesional', inplace=True)
df.replace(7428,'Poland Ekstraklasa', inplace=True)
df.replace(9553,'Poland Ekstraklasa', inplace=True)
df.replace(7731,'Portugal Liga NOS', inplace=True)
df.replace(9984,'Portugal Liga NOS', inplace=True)
df.replace(7732,'Portugal LigaPro', inplace=True)
df.replace(9704,'Portugal LigaPro', inplace=True)
df.replace(8741,'Republic of Ireland Premier Division', inplace=True)
df.replace(10946,'Republic of Ireland Premier Division', inplace=True)
df.replace(7663,'Romania Liga I', inplace=True)
df.replace(9622,'Romania Liga I', inplace=True)
df.replace(7573,'Russia Russian Premier League', inplace=True)
df.replace(9664,'Russia Russian Premier League', inplace=True)
df.replace(7494,'Scotland Premiership', inplace=True)
df.replace(9636,'Scotland Premiership', inplace=True)
df.replace(7492,'Serbia SuperLiga', inplace=True)
df.replace(10070,'Serbia SuperLiga', inplace=True)
df.replace(7958,'Slovakia Super Liga', inplace=True)
df.replace(9671,'Slovakia Super Liga', inplace=True)
df.replace(7526,'Slovenia PrvaLiga', inplace=True)
df.replace(9579,'Slovenia PrvaLiga', inplace=True)
df.replace(8781,'South America Copa Libertadores', inplace=True)
df.replace(10971,'South America Copa Libertadores', inplace=True)
df.replace(8899,'South Korea K League 1', inplace=True)
df.replace(11102,'South Korea K League 1', inplace=True)
df.replace(8938,'South Korea K League 2', inplace=True)
df.replace(11156,'South Korea K League 2', inplace=True)
df.replace(7665,'Spain La Liga', inplace=True)
df.replace(9665,'Spain La Liga', inplace=True)
df.replace(7592,'Spain Segunda División', inplace=True)
df.replace(9675,'Spain Segunda División', inplace=True)
df.replace(8737,'Sweden Allsvenskan', inplace=True)
df.replace(10969,'Sweden Allsvenskan', inplace=True)
df.replace(8738,'Sweden Superettan', inplace=True)
df.replace(10987,'Sweden Superettan', inplace=True)
df.replace(7496,'Switzerland Challenge League', inplace=True)
df.replace(9569,'Switzerland Challenge League', inplace=True)
df.replace(7504,'Switzerland Super League', inplace=True)
df.replace(9580,'Switzerland Super League', inplace=True)
df.replace(7768,'Turkey Süper Lig', inplace=True)
df.replace(9913,'Turkey Süper Lig', inplace=True)
df.replace(8777,'USA MLS', inplace=True)
df.replace(10977,'USA MLS', inplace=True)
df.replace(8937,'Uruguay Primera División', inplace=True)
df.replace(11209,'Uruguay Primera División', inplace=True)
df.replace(7620,'Wales Welsh Premier League', inplace=True)
df.replace(9565,'Wales Welsh Premier League', inplace=True)

In [9]:
def rename_leagues(df):
    df.replace(8595,'Argentina Primera División', inplace=True)
    df.replace(11212,'Argentina Primera División', inplace=True)
    df.replace(8008,'Australia A-League', inplace=True)
    df.replace(10505,'Australia A-League', inplace=True)
    df.replace(7584,'Austria 2. Liga', inplace=True)
    df.replace(9641,'Austria 2. Liga', inplace=True)
    df.replace(7890,'Austria Bundesliga', inplace=True)
    df.replace(9954,'Austria Bundesliga', inplace=True)
    df.replace(7572,'Belgium First Division B', inplace=True)
    df.replace(9607,'Belgium First Division B', inplace=True)
    df.replace(7544,'Belgium Pro League', inplace=True)
    df.replace(9577,'Belgium Pro League', inplace=True)
    df.replace(9035,'Brazil Serie A', inplace=True)
    df.replace(11321,'Brazil Serie A', inplace=True)
    df.replace(9042,'Brazil Serie B', inplace=True)
    df.replace(11351,'Brazil Serie B', inplace=True)
    df.replace(9087,'Brazil Serie C', inplace=True)
    df.replace(11365,'Brazil Serie C', inplace=True)
    df.replace(7483,'Bulgaria First League', inplace=True)
    df.replace(9551,'Bulgaria First League', inplace=True)
    df.replace(8833,'Chile Primera División', inplace=True)
    df.replace(11103,'Chile Primera División', inplace=True)
    df.replace(9186,'China Chinese Super League', inplace=True)
    df.replace(11217,'China Chinese Super League', inplace=True)
    df.replace(7457,'Croatia Prva HNL', inplace=True)
    df.replace(9542,'Croatia Prva HNL', inplace=True)
    df.replace(7586,'Czech Republic First League', inplace=True)
    df.replace(9592,'Czech Republic First League', inplace=True)
    df.replace(7426,'Denmark Superliga', inplace=True)
    df.replace(9545,'Denmark Superliga', inplace=True)
    df.replace(8520,'Egypt Egyptian Premier League', inplace=True)
    df.replace(10652,'Egypt Egyptian Premier League', inplace=True)
    df.replace(7593,'England Championship', inplace=True)
    df.replace(9663,'England Championship', inplace=True)
    df.replace(7570,'England EFL League One', inplace=True)
    df.replace(9582,'England EFL League One', inplace=True)
    df.replace(7574,'England EFL League Two', inplace=True)
    df.replace(9581,'England EFL League Two', inplace=True)
    df.replace(7704,'England Premier League', inplace=True)
    df.replace(9660,'England Premier League', inplace=True)
    df.replace(8898,'Estonia Meistriliiga', inplace=True)
    df.replace(11119,'Estonia Meistriliiga', inplace=True)
    df.replace(7455,'Europe UEFA Champions League', inplace=True)
    df.replace(9543,'Europe UEFA Champions League', inplace=True)
    df.replace(8935,'Finland Veikkausliiga', inplace=True)
    df.replace(11120,'Finland Veikkausliiga', inplace=True)
    df.replace(7500,'France Ligue 1', inplace=True)
    df.replace(9674,'France Ligue 1', inplace=True)
    df.replace(7501,'France Ligue 2', inplace=True)
    df.replace(9621,'France Ligue 2', inplace=True)
    df.replace(7499,'Germany 2. Bundesliga', inplace=True)
    df.replace(9656,'Germany 2. Bundesliga', inplace=True)
    df.replace(7591,'Germany 3. Liga', inplace=True)
    df.replace(9741,'Germany 3. Liga', inplace=True)
    df.replace(7664,'Germany Bundesliga', inplace=True)
    df.replace(9655,'Germany Bundesliga', inplace=True)
    df.replace(7954,'Greece Super League', inplace=True)
    df.replace(9889,'Greece Super League', inplace=True)
    df.replace(8784,'Iceland Úrvalsdeild', inplace=True)
    df.replace(10975,'Iceland Úrvalsdeild', inplace=True)
    df.replace(7608,'Italy Serie A', inplace=True)
    df.replace(9697,'Italy Serie A', inplace=True)
    df.replace(7864,'Italy Serie B', inplace=True)
    df.replace(9808,'Italy Serie B', inplace=True)
    df.replace(8810,'Japan J1 League', inplace=True)
    df.replace(10994,'Japan J1 League', inplace=True)
    df.replace(8811,'Japan J2 League', inplace=True)
    df.replace(10995,'Japan J2 League', inplace=True)
    df.replace(7484,'Netherlands Eerste Divisie', inplace=True)
    df.replace(9654,'Netherlands Eerste Divisie', inplace=True)
    df.replace(7482,'Netherlands Eredivisie', inplace=True)
    df.replace(9653,'Netherlands Eredivisie', inplace=True)
    df.replace(8739,'Norway Eliteserien', inplace=True)
    df.replace(10976,'Norway Eliteserien', inplace=True)
    df.replace(8740,'Norway First Division', inplace=True)
    df.replace(10986,'Norway First Division', inplace=True)
    df.replace(8783,'Paraguay Division Profesional', inplace=True)
    df.replace(11141,'Paraguay Division Profesional', inplace=True)
    df.replace(7428,'Poland Ekstraklasa', inplace=True)
    df.replace(9553,'Poland Ekstraklasa', inplace=True)
    df.replace(7731,'Portugal Liga NOS', inplace=True)
    df.replace(9984,'Portugal Liga NOS', inplace=True)
    df.replace(7732,'Portugal LigaPro', inplace=True)
    df.replace(9704,'Portugal LigaPro', inplace=True)
    df.replace(8741,'Republic of Ireland Premier Division', inplace=True)
    df.replace(10946,'Republic of Ireland Premier Division', inplace=True)
    df.replace(7663,'Romania Liga I', inplace=True)
    df.replace(9622,'Romania Liga I', inplace=True)
    df.replace(7573,'Russia Russian Premier League', inplace=True)
    df.replace(9664,'Russia Russian Premier League', inplace=True)
    df.replace(7494,'Scotland Premiership', inplace=True)
    df.replace(9636,'Scotland Premiership', inplace=True)
    df.replace(7492,'Serbia SuperLiga', inplace=True)
    df.replace(10070,'Serbia SuperLiga', inplace=True)
    df.replace(7958,'Slovakia Super Liga', inplace=True)
    df.replace(9671,'Slovakia Super Liga', inplace=True)
    df.replace(7526,'Slovenia PrvaLiga', inplace=True)
    df.replace(9579,'Slovenia PrvaLiga', inplace=True)
    df.replace(8781,'South America Copa Libertadores', inplace=True)
    df.replace(10971,'South America Copa Libertadores', inplace=True)
    df.replace(8899,'South Korea K League 1', inplace=True)
    df.replace(11102,'South Korea K League 1', inplace=True)
    df.replace(8938,'South Korea K League 2', inplace=True)
    df.replace(11156,'South Korea K League 2', inplace=True)
    df.replace(7665,'Spain La Liga', inplace=True)
    df.replace(9665,'Spain La Liga', inplace=True)
    df.replace(7592,'Spain Segunda División', inplace=True)
    df.replace(9675,'Spain Segunda División', inplace=True)
    df.replace(8737,'Sweden Allsvenskan', inplace=True)
    df.replace(10969,'Sweden Allsvenskan', inplace=True)
    df.replace(8738,'Sweden Superettan', inplace=True)
    df.replace(10987,'Sweden Superettan', inplace=True)
    df.replace(7496,'Switzerland Challenge League', inplace=True)
    df.replace(9569,'Switzerland Challenge League', inplace=True)
    df.replace(7504,'Switzerland Super League', inplace=True)
    df.replace(9580,'Switzerland Super League', inplace=True)
    df.replace(7768,'Turkey Süper Lig', inplace=True)
    df.replace(9913,'Turkey Süper Lig', inplace=True)
    df.replace(8777,'USA MLS', inplace=True)
    df.replace(10977,'USA MLS', inplace=True)
    df.replace(8937,'Uruguay Primera División', inplace=True)
    df.replace(11209,'Uruguay Primera División', inplace=True)
    df.replace(7620,'Wales Welsh Premier League', inplace=True)
    df.replace(9565,'Wales Welsh Premier League', inplace=True)

### Jogos do Dia

In [10]:
def fetch_matches(date, key, pages=3):
    dfs = []
    for page in range(1, pages + 1):
        url = f"https://api.football-data-api.com/todays-matches?key={key}&date={date}&page={page}"
        response = requests.get(url).json().get('data', [])
        if response:  
            temp_df = pd.DataFrame.from_dict(response)
            if 'competition_id' in temp_df.columns:
                dfs.append(temp_df)
    return pd.concat(dfs) if dfs else pd.DataFrame()

def process_matches(dates, key):
    all_matches = pd.concat([fetch_matches(date.strftime("%Y-%m-%d"), key) for date in dates], ignore_index=True)
    if not all_matches.empty and 'competition_id' in all_matches.columns:
        filtered_columns = [
            'competition_id', 'date_unix', 'game_week', 'home_name', 'away_name', 
            'odds_1st_half_result_1', 'odds_1st_half_result_x', 'odds_1st_half_result_2', 
            'odds_ft_1', 'odds_ft_x', 'odds_ft_2', 'odds_1st_half_over05', 'odds_1st_half_under05', 
            'odds_ft_over05', 'odds_ft_under05', 'odds_ft_over15', 'odds_ft_under15', 
            'odds_ft_over25', 'odds_ft_under25', 'odds_btts_yes', 'odds_btts_no', 
            'odds_doublechance_1x', 'odds_doublechance_12', 'odds_doublechance_x2', 
            'home_ppg', 'away_ppg', 'team_a_xg_prematch', 'team_b_xg_prematch', 'total_xg_prematch', 
            'odds_corners_1', 'odds_corners_x', 'odds_corners_2', 'odds_corners_over_75', 
            'odds_corners_under_75', 'odds_corners_over_85', 'odds_corners_under_85', 
            'odds_corners_over_95', 'odds_corners_under_95', 'odds_corners_over_105', 
            'odds_corners_under_105', 'odds_corners_over_115', 'odds_corners_under_115'
        ]
        all_matches = all_matches.loc[:, all_matches.columns.intersection(filtered_columns)]
        if 'date_unix' in all_matches.columns:
            all_matches['Data'] = pd.to_datetime(all_matches['date_unix'], unit='s') - pd.DateOffset(hours=3)
        return all_matches
    else:
        return pd.DataFrame()  

dates = [date.today() + timedelta(days=i) for i in range(3)]  
df0 = process_matches(dates, key)

In [11]:
df = df0[['competition_id','Data','game_week','home_name','away_name','odds_ft_1','odds_ft_x','odds_ft_2','odds_ft_over05','odds_ft_under05','odds_ft_over15','odds_ft_under15','odds_ft_over25','odds_ft_under25','odds_btts_yes','odds_btts_no','odds_doublechance_1x','odds_doublechance_12','odds_doublechance_x2']]
df.columns = ['League','Data','Rodada','Home','Away','Odd_H','Odd_D','Odd_A','Odd_Over05','Odd_Under05','Odd_Over15','Odd_Under15','Odd_Over25','Odd_Under25','Odd_BTTS_Yes','Odd_BTTS_No','Odd_DC_1X','Odd_DC_12','Odd_DC_X2']
df = drop_reset_index(df)
rename_leagues(df)

df = df.sort_values(['Data'])
df = df.drop_duplicates()
df = drop_reset_index(df)

df['Date'] = df['Data'].dt.date
df['Time'] = df['Data'].dt.time
df = df[['League','Date','Time','Rodada','Home','Away','Odd_H','Odd_D','Odd_A','Odd_Over05','Odd_Under05','Odd_Over15','Odd_Under15','Odd_Over25','Odd_Under25','Odd_BTTS_Yes','Odd_BTTS_No','Odd_DC_1X','Odd_DC_12','Odd_DC_X2']]
df

,League,Date,Time,Rodada,Home,Away,Odd_H,Odd_D,Odd_A,Odd_Over05,Odd_Under05,Odd_Over15,Odd_Under15,Odd_Over25,Odd_Under25,Odd_BTTS_Yes,Odd_BTTS_No,Odd_DC_1X,Odd_DC_12,Odd_DC_X2
1,Argentina Primera División,2024-04-05,21:00:00,13,Banfield,Independiente,2.80,3.10,2.70,1.11,6.18,1.63,2.29,3.10,1.36,2.38,1.53,1.50,1.35,1.42
2,Paraguay Division Profesional,2024-04-05,21:30:00,12,Nacional Asunción,Sportivo Ameliano,2.25,3.20,3.10,1.03,7.90,1.34,2.88,2.20,1.65,1.91,1.80,1.44,1.30,1.43
3,Australia A-League,2024-04-06,01:30:00,23,Western United,Macarthur,2.55,3.70,2.55,1.04,10.00,1.14,5.50,1.59,2.21,1.44,2.63,1.35,1.22,1.70
4,South Korea K League 1,2024-04-06,02:00:00,6,Ulsan,Suwon,1.60,4.00,5.00,1.05,9.50,1.22,4.00,1.68,2.10,1.80,1.91,1.13,1.20,2.35
5,Japan J1 League,2024-04-06,02:00:00,7,Consadole Sapporo,Gamba Osaka,2.57,3.56,2.42,1.04,10.00,1.22,4.20,1.70,2.10,1.53,2.30,1.45,1.25,1.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,Italy Serie A,2024-04-08,15:45:00,31,Udinese,Inter Milan,6.00,4.40,1.54,1.05,15.50,1.27,4.20,1.76,2.06,1.91,1.91,2.80,1.23,1.13
381,Portugal Liga NOS,2024-04-08,16:15:00,28,Casa Pia,GD Estoril Praia,2.46,3.25,2.73,0.00,0.00,0.00,0.00,1.86,1.94,0.00,0.00,0.00,0.00,0.00
382,Iceland Úrvalsdeild,2024-04-08,16:15:00,1,Breidablik,FH,1.75,3.80,3.60,1.01,10.75,1.13,5.10,1.44,2.63,1.43,2.50,1.24,1.22,1.88
383,Argentina Primera División,2024-04-08,20:00:00,13,Platense,Tigre,1.95,3.00,4.50,1.12,6.60,1.58,2.41,2.70,1.44,2.25,1.57,1.18,1.36,1.80
384,Argentina Primera División,2024-04-08,20:00:00,13,Godoy Cruz,Sarmiento,1.60,4.00,5.25,1.10,7.65,1.52,2.55,2.50,1.50,2.63,1.44,1.17,1.28,2.15

In [12]:
flt = df.Date == dates[0]
df0 = df[flt]
df0 = df0.sort_values(['Time'])
df0 = drop_reset_index(df0)
df0.to_excel(f'./FootyStats/Jogos_do_Dia/Jogos_do_Dia_FootyStats_{dates[0]}.xlsx',index=False)
display(df0)

,League,Date,Time,Rodada,Home,Away,Odd_H,Odd_D,Odd_A,Odd_Over05,Odd_Under05,Odd_Over15,Odd_Under15,Odd_Over25,Odd_Under25,Odd_BTTS_Yes,Odd_BTTS_No,Odd_DC_1X,Odd_DC_12,Odd_DC_X2
1,Australia A-League,2024-04-06,01:30:00,23,Western United,Macarthur,2.55,3.70,2.55,1.04,10.0,1.14,5.50,1.59,2.21,1.44,2.63,1.35,1.22,1.70
2,South Korea K League 1,2024-04-06,02:00:00,6,Ulsan,Suwon,1.60,4.00,5.00,1.05,9.5,1.22,4.00,1.68,2.10,1.80,1.91,1.13,1.20,2.35
3,Japan J1 League,2024-04-06,02:00:00,7,Consadole Sapporo,Gamba Osaka,2.57,3.56,2.42,1.04,10.0,1.22,4.20,1.70,2.10,1.53,2.30,1.45,1.25,1.53
4,South Korea K League 2,2024-04-06,02:00:00,5,Anyang,Ansan Greeners,1.45,4.50,6.00,1.04,10.0,1.22,4.00,1.66,2.15,1.73,2.00,1.11,1.22,2.45
5,Australia A-League,2024-04-06,03:30:00,23,Central Coast Mariners,Wellington Phoenix,1.75,3.75,4.50,1.03,13.0,1.22,4.00,1.75,2.05,1.70,2.05,1.21,1.22,1.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,Paraguay Division Profesional,2024-04-06,21:30:00,12,Libertad,Guaraní,1.47,3.51,4.94,1.01,10.5,1.22,3.70,1.88,1.88,1.83,1.83,1.03,1.22,2.40
208,Argentina Primera División,2024-04-06,21:30:00,13,Talleres Córdoba,Independiente Rivadavia,1.53,3.80,7.00,1.01,9.4,1.25,3.42,1.85,1.95,1.91,1.80,1.12,1.22,2.41
209,Argentina Primera División,2024-04-06,21:30:00,13,Unión Santa Fe,Belgrano,1.73,3.40,5.50,0.00,0.0,1.56,2.48,2.40,1.53,2.25,1.57,0.00,0.00,0.00
210,USA MLS,2024-04-06,21:30:00,7,St. Louis City,FC Dallas,1.87,3.85,3.90,1.03,13.0,1.25,3.75,1.76,2.04,1.70,2.05,1.22,1.22,2.00
211,USA MLS,2024-04-06,23:30:00,7,Seattle Sounders,Montreal Impact,1.75,3.90,4.50,1.05,7.8,1.25,3.50,1.97,1.89,1.91,1.91,1.11,1.28,2.05

In [13]:
flt = df.Date == dates[1]
df0 = df[flt]
df0 = df0.sort_values(['Time'])
df0 = drop_reset_index(df0)
df0.to_excel(f'./FootyStats/Jogos_do_Dia/Jogos_do_Dia_FootyStats_{dates[1]}.xlsx',index=False)
display(df0)

,League,Date,Time,Rodada,Home,Away,Odd_H,Odd_D,Odd_A,Odd_Over05,Odd_Under05,Odd_Over15,Odd_Under15,Odd_Over25,Odd_Under25,Odd_BTTS_Yes,Odd_BTTS_No,Odd_DC_1X,Odd_DC_12,Odd_DC_X2
1,Japan J1 League,2024-04-07,01:00:00,7,Tokyo Verdy,Kashiwa Reysol,2.69,3.35,2.62,1.08,7.50,1.42,2.80,2.25,1.61,1.95,1.80,1.45,1.28,1.45
2,Japan J2 League,2024-04-07,01:00:00,9,Roasso Kumamoto,V-Varen Nagasaki,2.77,3.30,2.40,1.05,8.50,1.28,3.40,1.93,1.93,1.73,2.00,1.55,1.28,1.40
3,Japan J2 League,2024-04-07,02:00:00,9,Tochigi,Renofa Yamaguchi,2.85,3.10,2.45,1.09,6.50,1.48,2.45,2.36,1.48,2.10,1.70,1.44,1.30,1.33
4,Australia A-League,2024-04-07,02:00:00,23,Newcastle Jets FC,Sydney FC,3.50,4.15,1.91,1.02,12.00,1.16,5.00,1.39,2.63,1.50,2.50,1.90,1.20,1.28
5,Japan J1 League,2024-04-07,02:00:00,7,Albirex Niigata,Cerezo Osaka,2.80,3.35,2.55,1.08,6.50,1.41,2.70,2.33,1.56,1.91,1.80,1.50,1.38,1.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,Chile Primera División,2024-04-07,18:30:00,7,Coquimbo Unido,Cobreloa,2.17,3.12,2.93,1.05,7.80,1.28,3.30,2.01,1.85,1.72,2.07,1.41,1.30,1.53
144,Argentina Primera División,2024-04-07,18:30:00,13,Racing Club,Lanús,2.00,3.40,3.80,1.07,7.61,1.44,2.72,2.35,1.57,2.10,1.67,1.25,1.28,1.85
145,Chile Primera División,2024-04-07,21:00:00,22,Unión Española,Universidad Chile,2.85,3.30,2.35,1.05,11.00,1.30,3.40,1.89,1.83,1.67,2.10,1.44,1.25,1.57
146,Argentina Primera División,2024-04-07,21:00:00,13,River Plate,Rosario Central,1.36,4.75,10.00,1.04,12.00,1.26,3.67,1.80,2.00,2.10,1.67,1.06,1.20,2.88
147,Paraguay Division Profesional,2024-04-07,21:00:00,12,2 de Mayo,Sportivo Luqueño,2.63,3.10,2.55,1.08,7.00,1.33,3.25,2.15,1.66,1.91,1.80,1.44,1.33,1.44

In [14]:
flt = df.Date == dates[2]
df0 = df[flt]
df0 = df0.sort_values(['Time'])
df0 = drop_reset_index(df0)
df0.to_excel(f'./FootyStats/Jogos_do_Dia/Jogos_do_Dia_FootyStats_{dates[2]}.xlsx',index=False)
display(df0)

,League,Date,Time,Rodada,Home,Away,Odd_H,Odd_D,Odd_A,Odd_Over05,Odd_Under05,Odd_Over15,Odd_Under15,Odd_Over25,Odd_Under25,Odd_BTTS_Yes,Odd_BTTS_No,Odd_DC_1X,Odd_DC_12,Odd_DC_X2
1,Russia Russian Premier League,2024-04-08,11:00:00,23,Orenburg,Rubin Kazan,2.55,3.10,2.85,1.05,7.20,1.40,2.73,2.40,1.58,1.95,1.81,1.45,1.36,1.52
2,Bulgaria First League,2024-04-08,11:00:00,28,Botev Vratsa,Levski Krumovgrad,2.87,2.87,2.62,1.06,6.70,1.48,2.45,2.37,1.53,2.05,1.72,1.44,1.30,1.33
3,Serbia SuperLiga,2024-04-08,11:00:00,29,IMT Novi Beograd,Napredak,2.40,3.10,3.00,1.04,7.80,1.35,2.84,2.18,1.67,1.83,1.83,1.36,1.28,1.55
4,Romania Liga I,2024-04-08,11:30:00,3,CSM Iaşi,U Craiova 1948,2.26,3.25,3.00,1.06,8.00,1.30,3.40,2.00,1.82,1.73,2.00,1.36,1.30,1.57
5,Bulgaria First League,2024-04-08,13:30:00,28,Lokomotiv Plovdiv,Cherno More,2.91,2.96,2.50,1.06,6.80,1.42,2.70,2.20,1.60,1.95,1.80,1.45,1.30,1.33
6,Serbia SuperLiga,2024-04-08,13:30:00,29,Javor Ivanjica,Mladost Lučani,2.25,3.10,3.25,0.00,0.00,0.00,0.00,2.18,1.67,0.00,0.00,0.00,0.00,0.00
7,Denmark Superliga,2024-04-08,14:00:00,2,Brøndby,Silkeborg,1.46,4.45,5.90,1.04,10.00,1.22,4.20,1.67,2.15,1.80,1.95,1.08,1.15,2.80
8,Sweden Allsvenskan,2024-04-08,14:00:00,2,Kalmar,Sirius,2.31,3.60,2.70,1.05,10.00,1.25,4.00,1.80,2.00,1.62,2.20,1.40,1.25,1.57
9,Sweden Superettan,2024-04-08,14:00:00,2,Oddevold,Örgryte,2.44,3.30,2.70,1.03,13.00,1.21,4.20,1.75,1.95,1.62,2.18,1.32,1.28,1.64
10,Poland Ekstraklasa,2024-04-08,14:00:00,27,Zagłębie Lubin,Górnik Zabrze,2.18,3.35,3.20,1.05,8.50,1.30,3.30,1.89,1.88,1.70,2.05,1.35,1.33,1.65
11,Portugal LigaPro,2024-04-08,14:00:00,28,Academico Viseu,Porto II,2.45,3.40,2.90,1.04,8.50,1.29,3.30,1.95,1.89,1.70,2.05,1.35,1.27,1.45
12,Sweden Allsvenskan,2024-04-08,14:10:00,2,Djurgården,Häcken,1.95,3.85,3.25,1.04,11.00,1.20,4.50,1.67,2.15,1.57,2.25,1.22,1.20,2.00
13,Romania Liga I,2024-04-08,14:30:00,3,Oţelul Galaţi,Dinamo Bucureşti,2.13,3.05,3.50,1.11,6.00,1.49,2.55,2.45,1.50,2.05,1.70,1.25,1.36,1.70
14,Netherlands Eerste Divisie,2024-04-08,15:00:00,33,Ajax II,Den Bosch,1.75,3.50,5.00,1.02,18.00,1.16,4.60,1.57,2.35,1.53,2.38,1.22,1.25,1.90
15,Netherlands Eerste Divisie,2024-04-08,15:00:00,33,AZ II,Emmen,2.50,3.50,2.70,1.02,16.00,1.18,4.25,1.62,2.25,1.53,2.38,1.45,1.25,1.52
16,Netherlands Eerste Divisie,2024-04-08,15:00:00,33,Utrecht II,Willem II,10.00,5.00,1.33,1.01,11.00,1.15,4.75,1.57,2.35,1.83,1.83,3.10,1.17,1.09
17,Spain Segunda División,2024-04-08,15:30:00,34,Racing Santander,AD Alcorcón,1.76,3.50,4.40,1.07,8.00,1.38,2.95,2.16,1.70,1.95,1.73,1.18,1.25,2.00
18,Argentina Primera División,2024-04-08,15:30:00,13,Deportivo Riestra,Huracán,3.40,3.00,2.30,1.12,5.87,1.61,2.33,2.88,1.40,2.38,1.53,1.55,1.40,1.30
19,France Ligue 2,2024-04-08,15:45:00,31,Auxerre,Troyes,1.42,4.30,5.40,1.03,9.00,1.17,4.30,1.57,2.25,1.75,1.93,1.11,1.15,2.62
20,Italy Serie A,2024-04-08,15:45:00,31,Udinese,Inter Milan,6.00,4.40,1.54,1.05,15.50,1.27,4.20,1.76,2.06,1.91,1.91,2.80,1.23,1.13
21,Portugal Liga NOS,2024-04-08,16:15:00,28,Casa Pia,GD Estoril Praia,2.46,3.25,2.73,0.00,0.00,0.00,0.00,1.86,1.94,0.00,0.00,0.00,0.00,0.00
22,Iceland Úrvalsdeild,2024-04-08,16:15:00,1,Breidablik,FH,1.75,3.80,3.60,1.01,10.75,1.13,5.10,1.44,2.63,1.43,2.50,1.24,1.22,1.88
23,Argentina Primera División,2024-04-08,20:00:00,13,Platense,Tigre,1.95,3.00,4.50,1.12,6.60,1.58,2.41,2.70,1.44,2.25,1.57,1.18,1.36,1.80
24,Argentina Primera División,2024-04-08,20:00:00,13,Godoy Cruz,Sarmiento,1.60,4.00,5.25,1.10,7.65,1.52,2.55,2.50,1.50,2.63,1.44,1.17,1.28,2.15

### Bases de Dados

In [ ]:
def fetch_and_process_matches(league, season_id, year, key):
    url = f"https://api.football-data-api.com/league-matches?key={key}&season_id={season_id}"
    response = requests.get(url).json()['data']
    df = pd.DataFrame.from_dict(response)
    df['League'] = league
    df = df[['id','League','season','status','date_unix','game_week','home_name','away_name',
                 'homeGoalCount','awayGoalCount','totalGoalCount',
                 'homeGoals','awayGoals',
                 'odds_ft_1','odds_ft_x','odds_ft_2',
                 'odds_ft_over05','odds_ft_under05','odds_ft_over15','odds_ft_under15','odds_ft_over25','odds_ft_under25',
                 'odds_btts_yes','odds_btts_no','odds_doublechance_1x','odds_doublechance_12','odds_doublechance_x2']]
    df.columns = ['Id_Jogo','League','Season','Status','Data','Rodada','Home','Away',
                      'Goals_H','Goals_A','TotalGoals',
                      'Goals_H_Minutes','Goals_A_Minutes',
                      'Odd_H','Odd_D','Odd_A',
                      'Odd_Over05','Odd_Under05','Odd_Over15','Odd_Under15','Odd_Over25','Odd_Under25',
                      'Odd_BTTS_Yes','Odd_BTTS_No','Odd_DC_1X','Odd_DC_12','Odd_DC_X2']
    df['Data'] = pd.to_datetime(df['Data'], unit='s') - pd.DateOffset(hours=3)
    df = df.sort_values(['Data'])
    df = df[df.Status == 'complete']
    df['Date'] = df['Data'].dt.date
    df['Time'] = df['Data'].dt.time
    df = df[['League','Season','Date','Time','Rodada','Home','Away',
             'Goals_H','Goals_A','TotalGoals',
             'Goals_H_Minutes','Goals_A_Minutes',
             'Odd_H','Odd_D','Odd_A',
             'Odd_Over05','Odd_Under05','Odd_Over15','Odd_Under15','Odd_Over25','Odd_Under25',
             'Odd_BTTS_Yes','Odd_BTTS_No','Odd_DC_1X','Odd_DC_12','Odd_DC_X2']]
    df = drop_reset_index(df)

    filepath = f'./FootyStats/Bases_de_Dados/{league}_{year}.xlsx'
    df.to_excel(filepath, index=False)
    print(f"{league} - {year} - Salvo com Sucesso!")
    
for i, j, k in zip(new2.League, new2.ID, new2.Season):
    fetch_and_process_matches(str(i), str(j), str(k), key)

Argentina Primera División - 2023 - Salvo com Sucesso!
Argentina Primera División - 2024 - Salvo com Sucesso!
Australia A-League - 20222023 - Salvo com Sucesso!
Australia A-League - 20232024 - Salvo com Sucesso!
Austria 2. Liga - 20222023 - Salvo com Sucesso!
Austria 2. Liga - 20232024 - Salvo com Sucesso!
Austria Bundesliga - 20222023 - Salvo com Sucesso!
Austria Bundesliga - 20232024 - Salvo com Sucesso!
Belgium First Division B - 20222023 - Salvo com Sucesso!
Belgium First Division B - 20232024 - Salvo com Sucesso!
Belgium Pro League - 20222023 - Salvo com Sucesso!
Belgium Pro League - 20232024 - Salvo com Sucesso!
Brazil Serie A - 2023 - Salvo com Sucesso!
Brazil Serie A - 2024 - Salvo com Sucesso!
Brazil Serie B - 2023 - Salvo com Sucesso!
Brazil Serie B - 2024 - Salvo com Sucesso!
Brazil Serie C - 2023 - Salvo com Sucesso!
Brazil Serie C - 2024 - Salvo com Sucesso!
Bulgaria First League - 20222023 - Salvo com Sucesso!
Bulgaria First League - 20232024 - Salvo com Sucesso!
Chile Primera División - 2023 - Salvo com Sucesso!
Chile Primera División - 2024 - Salvo com Sucesso!
China Chinese Super League - 2023 - Salvo com Sucesso!
China Chinese Super League - 2024 - Salvo com Sucesso!
Croatia Prva HNL - 20222023 - Salvo com Sucesso!
Croatia Prva HNL - 20232024 - Salvo com Sucesso!
Czech Republic First League - 20222023 - Salvo com Sucesso!
Czech Republic First League - 20232024 - Salvo com Sucesso!
Denmark Superliga - 20222023 - Salvo com Sucesso!
Denmark Superliga - 20232024 - Salvo com Sucesso!
Egypt Egyptian Premier League - 20222023 - Salvo com Sucesso!
Egypt Egyptian Premier League - 20232024 - Salvo com Sucesso!
England Championship - 20222023 - Salvo com Sucesso!
England Championship - 20232024 - Salvo com Sucesso!
England EFL League One - 20222023 - Salvo com Sucesso!
England EFL League One - 20232024 - Salvo com Sucesso!
England EFL League Two - 20222023 - Salvo com Sucesso!
England EFL League Two - 20232024 - Salvo com Sucesso!
England Premier League - 20222023 - Salvo com Sucesso!
England Premier League - 20232024 - Salvo com Sucesso!
Estonia Meistriliiga - 2023 - Salvo com Sucesso!
Estonia Meistriliiga - 2024 - Salvo com Sucesso!
Europe UEFA Champions League - 20222023 - Salvo com Sucesso!
Europe UEFA Champions League - 20232024 - Salvo com Sucesso!
Finland Veikkausliiga - 2023 - Salvo com Sucesso!
Finland Veikkausliiga - 2024 - Salvo com Sucesso!
France Ligue 1 - 20222023 - Salvo com Sucesso!
France Ligue 1 - 20232024 - Salvo com Sucesso!
France Ligue 2 - 20222023 - Salvo com Sucesso!
France Ligue 2 - 20232024 - Salvo com Sucesso!
Germany 2. Bundesliga - 20222023 - Salvo com Sucesso!
Germany 2. Bundesliga - 20232024 - Salvo com Sucesso!
Germany 3. Liga - 20222023 - Salvo com Sucesso!
Germany 3. Liga - 20232024 - Salvo com Sucesso!
Germany Bundesliga - 20222023 - Salvo com Sucesso!
Germany Bundesliga - 20232024 - Salvo com Sucesso!
Greece Super League - 20222023 - Salvo com Sucesso!
Greece Super League - 20232024 - Salvo com Sucesso!
Iceland Úrvalsdeild - 2023 - Salvo com Sucesso!
Iceland Úrvalsdeild - 2024 - Salvo com Sucesso!
Italy Serie A - 20222023 - Salvo com Sucesso!
Italy Serie A - 20232024 - Salvo com Sucesso!
Italy Serie B - 20222023 - Salvo com Sucesso!
Italy Serie B - 20232024 - Salvo com Sucesso!
Japan J1 League - 2023 - Salvo com Sucesso!
Japan J1 League - 2024 - Salvo com Sucesso!
Japan J2 League - 2023 - Salvo com Sucesso!
Japan J2 League - 2024 - Salvo com Sucesso!
Netherlands Eerste Divisie - 20222023 - Salvo com Sucesso!
Netherlands Eerste Divisie - 20232024 - Salvo com Sucesso!
Netherlands Eredivisie - 20222023 - Salvo com Sucesso!
Netherlands Eredivisie - 20232024 - Salvo com Sucesso!
Norway Eliteserien - 2023 - Salvo com Sucesso!
Norway Eliteserien - 2024 - Salvo com Sucesso!
Norway First Division - 2023 - Salvo com Sucesso!
Norway First Division - 2024 - Salvo com Sucesso!
Paraguay Division Profesional - 2023 - Salvo com Sucesso!
Paraguay Division Profesional - 2024 - Salvo com Sucesso!
Poland Ekstraklasa - 20222023 - Salvo com Sucesso!
Poland Ekstraklasa - 20232024 - Salvo com Sucesso!
Portugal Liga NOS - 20222023 - Salvo com Sucesso!
Portugal Liga NOS - 20232024 - Salvo com Sucesso!
Portugal LigaPro - 20222023 - Salvo com Sucesso!
Portugal LigaPro - 20232024 - Salvo com Sucesso!
Republic of Ireland Premier Division - 2023 - Salvo com Sucesso!
Republic of Ireland Premier Division - 2024 - Salvo com Sucesso!
Romania Liga I - 20222023 - Salvo com Sucesso!
Romania Liga I - 20232024 - Salvo com Sucesso!
Russia Russian Premier League - 20222023 - Salvo com Sucesso!
Russia Russian Premier League - 20232024 - Salvo com Sucesso!
Scotland Premiership - 20222023 - Salvo com Sucesso!
Scotland Premiership - 20232024 - Salvo com Sucesso!
Serbia SuperLiga - 20222023 - Salvo com Sucesso!
Serbia SuperLiga - 20232024 - Salvo com Sucesso!
Slovakia Super Liga - 20222023 - Salvo com Sucesso!
Slovakia Super Liga - 20232024 - Salvo com Sucesso!
Slovenia PrvaLiga - 20222023 - Salvo com Sucesso!
Slovenia PrvaLiga - 20232024 - Salvo com Sucesso!
South America Copa Libertadores - 2023 - Salvo com Sucesso!